### ISSUE TITLE
NBA, MLB Draftking Optimizer Error with Pulp package.

### ISSUE THREAD

**Issue by cpduran0622** [DimaKudosh/pydfs-lineup-optimizer#267]
Hi, there.
I have updated pydfs-lineup-optimizer to 3.5.0 recently.
And I am having errors for draftkings sports.

![image](https://user-images.githubusercontent.com/73656396/117196517-27cb9180-ae19-11eb-998f-5feced18b65f.png)

Could you fix it, please?
Thanks

**Comment by sansbacon** [comment]
You would have to provide more detail about your code to troubleshoot this error.

**Comment by cpduran0622** [comment]
![image](https://user-images.githubusercontent.com/73656396/117374229-591e8d00-aeff-11eb-9d72-18b623370b50.png)

**Comment by cpduran0622** [comment]
Hi, thanks for your reply.
I just used custom players for draftkings nba.

`optimizer.load_players(players)  # players is list of Player objects`

**Comment by cpduran0622** [comment]
If I use csv file, it is working well.

```
csv_filename = "dk_nba.csv"
optimizer = get_optimizer(Site.DRAFTKINGS, Sport.BASKETBALL)
optimizer.load_players_from_csv(csv_filename)
lineups = optimizer.load_lineups_from_csv(csv_filename)
for lineup in optimizer.optimize_lineups(lineups):
    print(lineup)
```

**Comment by cpduran0622** [comment]
I am just getting errors when I am using `optimizer.load_players(players)`.

**Comment by sansbacon** [comment]
My guess is that there is something wrong with your players object. Start by looking at type(players). It should be a list. Then confirm that every item in the list is a Player object. From the error message that you posted, it isn't clear what the problem is.

**Comment by cpduran0622** [comment]
Thank you, @sansbacon .
And my code worked version 3.4.
After to update to 3.5, this error happens.

**Comment by edoublin** [comment]
@DimaKudosh Can you look over this and give any insight? Thank you

**Comment by cpduran0622** [comment]
Thank you to your response.

`        player_for_add = Player(
                            player_id=player_id,
                            first_name=first_name,
                            last_name=last_name,
                            positions=positions,
                            team=team,
                            salary=salary,
                            fppg=fppg,
                            is_injured=is_injured,
                            is_confirmed_starter=False,
                        )`

It is player object for nba I used

**Comment by DimaKudosh** [comment]
It's not clear what do you store in variables that you pass to the player constructor. Probably it's a problem with the rule of the minimum game in draftkings nba, as I can see you don't provide information about game. You can try to disable this constraint by adding this line before calling optimize method:
`optimizer.settings.min_games = None`
If it start working it's mean that you also need to provide game_info parameter to each player as I can do when parsing csv file: https://github.com/DimaKudosh/pydfs-lineup-optimizer/blob/master/pydfs_lineup_optimizer/sites/draftkings/classic/importer.py#L65

**Comment by cpduran0622** [comment]
`player_for_add.game_info = GameInfo(team, player['opp'], '' , '')`

I have added game info with it.
And it worked with 3.4.2.
Maybe did you changed game info model?

**Comment by cpduran0622** [comment]
yeah, that's good.
And I just tested old GameInfo namedtuple in 3.5.0.
It works for me.
And in this case late swap is not working.
I am getting below error.
```
    game_info = GameInfo(home_team, away_team, None)
TypeError: __new__() missing 1 required positional argument: 'game_started'
```

What is your think?

**Comment by DimaKudosh** [comment]
GameInfo accepts 4 parameters:
```
game_info = GameInfo(home_team, away_team, None, False)
```

**Comment by cpduran0622** [comment]
Yes! It works for me.
Thank you.
