### ISSUE TITLE
ImportError: cannot import name 'clock' from 'time' (unknown location)

### ISSUE THREAD

**Issue by mikebencho** [DimaKudosh/pydfs-lineup-optimizer#116]
Hi 

I'm getting this error 
"C:\Users\Mike\AppData\Local\Programs\Python\Python38\lib\site-packages\pulp\solvers.py", line 35, in <module>
    from time import clock
ImportError: cannot import name 'clock' from 'time' (unknown location)

Any advice?
(i barely know what i'm doing in python) so if this is just me doing something wrong please ignore
seems like this was depricated in 3.8 (which is the version i have)
https://github.com/PyTables/PyTables/issues/744

Thanks
Mike

**Comment by DimaKudosh** [comment]
Hi, this library doesn't work with python 3.8 because it depends on pulp library that doesn't support python 3.8 at the moment. They already have [PR](https://github.com/coin-or/pulp/pull/237) with this issue so I think it'll be fixed in the near feature.

**Comment by DimaKudosh** [comment]
New version of library should work with python 3.8
